config/routes.rb
Rails.application.routes.draw do
  get 'ui(/:action)', controller: 'ui'

  #site root
  root 'businesses#index'
  get '/home', to: 'reviews#index'

  #Session
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'session#destroy'

  #Reviews
  resources :reviews, only: [:index, :create]

  #Categories
  resources :categories, only: [:show]

  #Businesses
  resources :businesses, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:index, :create]
  end


  #Users
  get 'register', to: 'users#new'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy'
  resources :users, only: [:create, :show]
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :category
  has_many :reviews
  validates_presence_of :name, :description, :picture_url
  validates_uniqueness_of :name
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :businesses
  validates_presence_of :name

  def recent_businesses
    businesses.first(6)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :business

  validates_presence_of :description

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews

  has_secure_password

  validates_presence_of :email
  validates_uniqueness_of :email

  def recent_reviews
    reviews.first(6)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_user
    redirect_to sign_in_path unless current_user
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def new
    @business = Business.new
  end

  def create
    @business = Business.new(params[:business].permit(:name, :description, :picture_url, :category_id))

    if @business.save
      flash[:success] = "New Business listed!"
      redirect_to businesses_path
    else
      flash.now[:danger] = "There were something missing."
      render :new
    end
  end

  def index
    @categories = Category.all
  end

  def show
    @business = Business.find(params[:id])
    @reviews = @business.reviews.all if @business
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/category_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :require_user

  def index
    @reviews = Review.first(25)
  end

  def create
    @business = Business.find(params[:business_id])
    review = @business.reviews.build(review_params.merge!(user: current_user))
    if review.save
      redirect_to @business
    else
      @reviews = @business.reviews.reload
      redirect_to @business
    end
  end

  private

  def review_params
    params.require(:review).permit(:description)
  end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to home_path if current_user
  end

  def create
    user = User.where(email: params[:email]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to home_path, notice: 'You are signed in, enjoy!'
    else
      flash[:error] = "Invalid email or password."
      redirect_to sign_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You are signed out"
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  before_filter do
    redirect_to :root if Rails.env.production?
  end

  layout "application"

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to sign_in_path
    else
      render :new
    end
  end

  def show
    if current_user.id == params[:id].to_i
      @user = current_user
      @reviews = current_user.reviews
    else
      @user = User.find(params[:id])
      @reviews = @user.reviews
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/index.html.haml
%article.business_category.container
  %header
    - @categories.each do |category|
      %br
      %h2 #{category.name}
      .video.row
        - category.recent_businesses.each do |business|
          .video.col-sm-2
            =link_to business do
              %h3= link_to business.name, business_path(business)
              =image_tag business.picture_url

app/views/businesses/new.html.haml
%section.admin_add_video
  .container
    .row
      .com-md-10.col-md-offset-1
        = bootstrap_form_for @business, layout: :horizontal, control_col: "col-sm-6" do |f|
          %h3 Add a New Business
          %br
          %fieldset
            = f.text_field :name, label: "Business Name"
            = f.text_area :description
            = f.select :picture_url, [["Tokyo","/images/japanese-food-166-236.png"],
                                      ["Beijing","/images/chinese-food-166-236.png"],
                                      ["PizzaHut","/images/pizza-166.236.png"]],
                       { label: "Choose a picture:" }, { class: "selectpicker" }
            = f.collection_radio_buttons :category_id, Category.all, :id, :name do |cb| 
              cb.label(class: "checkbox inline") { cb.check_box(class: "checkbox") + cb.text }
            = f.submit "Add the Business", class: "btn btn-default"

app/views/businesses/show.html.haml
%article.video
  .container
    .row
      .video_large_cover.col-sm-7.col-sm-offset-1
        =image_tag @business.picture_url
      .video_info.col-sm-3
        %header
          %h3= @business.name
        %p= @business.description

%section.reviews.container
  .row
    .col-sm-7.col-sm-offset-1
      = bootstrap_form_for [@business, Review.new] do |f|
        = f.text_area :description, label: "Write Review", rows: 6
        = f.hidden_field :business, value: @business.id, name:"review[business_id]"
        = f.submit "Submit", class: "btn btn-default"
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h3= "User Review (#{@reviews.count})"
      %ul
        - @reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %p!= "by <a href=#{user_path(review.user)}>#{review.user.username}</a>"
              .col-sm-8
                %p= review.description

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title Yelp
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tag
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
  %body
    %header
      = render 'shared/header'
    %section.content.clearfix
      = render 'shared/messages'
      = yield
    %footer
      &copy 2016 Yelp

app/views/reviews/index.html.haml
%section.review.container
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h1 Recent reviews
        %ul
          - @reviews.each do |review|
            %article.review
              %li.row
                .col-sm-2
                  %h2= link_to review.business.name, business_path(review.business.id)
                .col-sm-8
                  %p= review.description

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.col-md-2
    = link_to "Yelp"
  - if current_user
    %ul.col-md-4.clearfix
      %li= link_to "Businesses", businesses_path
      %li= link_to "Add a Business", new_business_path
      %li= link_to "My Review", user_path(current_user.id)
      %li= link_to "Recent Reviews", reviews_path
    #user_links.pull-right
      %ul
        %li.dropdown
          %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
            Welcome, #{current_user.username}
            %b.caret
          %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
            %li= link_to "My Profile", user_path(current_user.id) 
            %li.divider(role="separator")
            %li= link_to "Sign Out", sign_out_path 
  - else
    %ul.col-md-4.clearfix.pull-right
      %li= link_to "Sign in", sign_in_path
      %li= link_to "Reginster", register_path

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/ui/add_business.html.haml
%section.admin_add_video
  .container
    .row
      .col-md-10.col-md-offset-1
        %form.form-horizontal
          %h3 Add a New Business
          %br
          %fieldset
            .form-group
              %label.control-label.col-sm-3 Title
              .col-sm-3
                %input.form-control(type="text")
            .form-group
              %label.control-label.col-sm-3 Category
              .col-sm-6
                %select.form-control
            .form-group
              %label.control-label.col-sm-3 Description
              .col-sm-6
                %textarea.form-control(rows="8")
            .form-group
              %label.control-label.col-sm-3 Large Cover
              .col-sm-6
                %col.btn.btn-file
                  %input.form-control(type="file")
            .form-group
              %label.control-label.col-sm-3 Small Cover
              .col-sm-6
                %col.btn.btn-file
                  %input.form-control(type="file")

          %fieldset.actions.form-group
            .col-sm-6.col-md-offset-3
              %input(type="submit" value="Add Business" class="btn btn-default")

app/views/ui/business.html.haml
%article.business
  .row
    .col-md-3.col-md-offset-1
      %header
        %h3= link_to "Japanese Food"
      - 3.times do
        .videos.row
          .vidoe.col-sm-6
            = link_to "", nil do
              %img(src="/images/japanese-food-166-236.png")
          .review.col-sm-6
            %p Reviews (5/5)
          .col-sm-12
            %h6 Tokyo Restaurant
        %hr
    .col-md-3.col-md-offset-1
      %header
        %h3= link_to "Chinese"
      - 3.times do
        .videos.row
          .video.col-sm-6
            = link_to "", nil do
              %img(src="/images/chinese-food-166-236.png")
          .review.col-sm-6
            %p Reviews (5/5)
          .col-sm-12
            %h6 Beijing Restaurant
        %hr
    .col-md-3.col-md-offset-1
      %header
        %h3= link_to "Pizza"
      - 3.times do
        .videos.row
          .video.col-sm-6
            = link_to "", nil do
              %img(src="/images/pizza-166-236.png")
          .review.col-sm-6
            %p Reviews (5/5)
          .col-sm-12
            %h6 Pizza Hut
        %hr

app/views/ui/index.html.haml
%section.ui-index
  %ul
    - Dir.glob('app/views/ui/*.html.haml').sort.each do |file|
      - wireframe = File.basename(file,'.html.haml')
      -  unless wireframe == 'index' || wireframe.match(/^_/)
        %li= link_to wireframe.titleize, action: wireframe unless wireframe == 'index'

app/views/ui/register.html.haml
%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      %form.form-horizontal
        %header
          %h1 Register
        %fieldset
          .form-group
            %label.control-label.col-sm-2 Email Address
            .col-sm-6
              %input.form-control(type="email")
          .form-group
            %label.control-label.col-sm-2 Password
            .col-sm-6
              %input.form-control(type="password")
          .form-group
            %label.control-label.col-sm-2 Full Name
            .col-sm-6
              %input.form-control(type="text")
        %fieldset.actions.control-group.col-sm-offset-2
          .controls
            %input(type="submit" value="Sign Up" class="btn btn-default")

app/views/ui/sign_in.html.haml
%section.sign_in.container
  .row
    .col-sm-10.col-sm-offset-1
      %form.sign_in
        %header
          %h1 Sign in
        %fieldset
          .form-group
            %label Email Address
            .row
              .col-sm-4
                %input.form-control(type="email")
          .form-group
            %label Password
            .row
              .col-sm-4
                %input.form-control(type="password")
        %fieldset.form-group.action
          .controls
            %input(type="submit" value="Sign in" class="btn btn-default")

app/views/ui/user.html.haml
%section.user.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          %img(src="http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest('fat.fox@gmail.com'.downcase)}?s=40")
          %h2 My Favorites  (8)
        %table.table
          %thead
            %tr
              %th(width="30%") Name
              %th(width="15%") Category
          %tbody
            - 8.times do
              %tr
                %td
                  = link_to "Sushi"
                %td
                  = link_to "Japanese Food"

%section.user_reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h3 My Reviews (253)
      %ul
        - 8.times do
          %article.review
            %li.row
              .col-sm-2
                %p
                  = link_to "\"Sushi\""
                %col Rating: 5 / 5
              .col-sm-8
                %p In my opinion, this is one of the best shows ever made. It's not only funny, but despite being so frequently silly, it's very smart as well. Math, science, history, all get referenced. The best parts of the show are the subtle things, those little things in the background or just on screen for a couple of seconds that just make you laugh out loud if you were paying attention. The writers even appear to have been thinking ahead, because if you play close attention to the first episode, you can see a literal shadow of an event revealed seasons later.

app/views/users/new.html.haml
%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_for @user, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-4" do |f|
        %header
          %h1 Register
        = f.alert_message "Please fix the error below"
        = f.email_field :email, label: "Email Address"
        = f.password_field :password
        = f.text_field :username, label: "User name"
        = f.submit 'Sign Up', class: 'col-sm-offset-2 btn btn-default'

app/views/users/show.html.haml
%section.user.container
  %section.user_review.container
    .row
      .col-sm-10.col-sm-offset-1
        %header
          %h3= "#{@user.username}'s Reviews (#{@reviews.count})"
        %url
          - @reviews.each do |review|
            %article.review
              %li.row.list-group-item
                .col-sm-2
                  %p
                    = link_to "\"#{review.business.name}\"", business_path(review.business)
                .col-sm-8
                  %p= review.description